### ISSUE TITLE
Feature Request: Logging Options

### ISSUE THREAD

**Issue by Wortex17** [Spark-NF/hls-downloader#11]
Currently the hls download spams the console with its progress messages as well as with subsequent ffmpeg output.
It would be great if we could at least enable/disable either of those.
As a next step we should be able to provide our own logging method so we can reroute this into the log framework the rest of the application uses.

**Comment by Spark-NF** [comment]
I just introduced a `--quiet` CLI parameter, and a `logger` config option for the API.
You can find the documentation in the [README](https://github.com/Spark-NF/hls-downloader#--quiet-logger).
