### ISSUE TITLE
How can i use this ?

### ISSUE THREAD

**Issue by phanluchoaofficial20** [Spark-NF/hls-downloader#17]
Hi,

I have download newest realease but I don't know how to use it and i already see a usage but is use for CLI but in release I don't see CLI on folder. Can anyone help me give a guide for using this ?

Thanks!

**Comment by Spark-NF** [comment]
Hello,

You can install it globally with npm (`npm i -g node-hls-downloader`) then `hls-downloader` should be in your path.
You could also run it with npx (`npx node-hls-downloader ...`).
